### ISSUE TITLE
Dynamically-assembled require() calls in lib/widget.js break Browserify support

### ISSUE THREAD

**Issue by lostfictions** [chjj/blessed#158]
Looks like the refactoring introduced by 8d11075b891ca2dd7aaeb2777a4e6e632d3875e8 means those `require` calls can't be resolved by bundling tools like Browserify.

Wasn't too hard for me to fix myself, but I imagine I'm not the only one using this with Browserify -- there was some talk in chjj/tty.js#106 about it.

**Comment by chjj** [comment]
Ah, I see:

``` bash
[user@node blessed]$ node bundle.js
module.js:338
    throw err;
          ^
Error: Cannot find module './widgets/node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at s (/home/user/work/node_modules/blessed/bundle.js:1:176)
    at /home/user/work/node_modules/blessed/bundle.js:1:367
    at /home/user/work/node_modules/blessed/bundle.js:13553:33
    at Array.forEach (native)
    at Object.<anonymous> (/home/user/work/node_modules/blessed/bundle.js:13551:16)
    at s (/home/user/work/node_modules/blessed/bundle.js:1:316)
```

I guess we could require them all at once again instead of using a forEach.

**Comment by chjj** [comment]
I added a stupid transform workaround that's sort of flimsy, but it allows me to avoid changing any code in widget.js.

**Comment by chjj** [comment]
Just made it a bit less insane, in case widget.js is ever changed.

**Comment by chjj** [comment]
Refactored it a bit. Should work now. Trying browserifying it and let me know.

**Comment by lostfictions** [comment]
Amazing, thanks!

Unfortunately, looks like the widget API isn't compatible with Browserify -- looks like Screen implicitly depends on tput, even if it's passed an existing Program initialized `tput: false` (at https://github.com/chjj/blessed/blob/master/lib/widgets/screen.js#L61) -- couldn't figure out a sensible way to get around this.

**Comment by chjj** [comment]
Yeah, `tput` is going to have to read the terminfo file, however, it will fallback to a builtin vt102 termcap, or, if browserify can manage it: an xterm terminfo file. We _could_ include this in tput.js as a fallback if necessary I suppose.

**Comment by lostfictions** [comment]
I can't seem to convince tput to use the fallback -- even if I call `tput._useVt102Cap()` it still seems to want to read the terminfo from the disk, which again breaks the Browserify bundle.

It should be doable to inline the xterm terminfo with https://github.com/substack/brfs -- but like the widget requires, it doesn't look like the way `readFileSync` is called in `tput.js` is statically resolvable.

**Comment by chjj** [comment]
@lostfictions, if you give me a PR that's relatively unobtrusive, I'll glady merge it.

**Comment by chjj** [comment]
@lostfictions, I added a fix for tput.js to compile in the xterm terminfo for the browser. Let me know how it works.

**Comment by lostfictions** [comment]
It works! Amazing! Thanks so much.

**Comment by chjj** [comment]
Awesome. Good to know we got that squared away. Just curious, if I may ask: what are you working on for the browser?

**Comment by lostfictions** [comment]
It's a bit frivolous -- I'm working on a (browser-based) game about a sort of byzantine old terminal interface, so blessed+term.js seemed like a natural fit!

I was getting really excited looking at `blessed-contrib`'s extra widgets, too. It looks like they don't render correctly in term.js though -- it just outputs ? instead of certain characters. (Doesn't seem to be a font/styling issue, either -- `?` is the actual character it writes to the DOM. I have no idea how to diagnose or debug this...)

**Comment by yaronn** [comment]
wrt blessed-contrib, possibly you do not have braille fonts.

do components that do not use braille font render correctly? (e.g. bar
chart)
if you are using windows, can you try do it from an ubuntu VM which
natively supports braille?

On Tue, Jul 28, 2015 at 12:28 PM, s <notifications@github.com> wrote:

> It's a bit frivolous -- I'm working on a (browser-based) game about a sort
> of byzantine old terminal interface, so blessed+term.js seemed like a
> natural fit!
>
> I was getting really excited looking at blessed-contrib's extra widgets,
> too. It looks like they don't render correctly in term.js though -- it just
> outputs ? instead of certain characters. (Doesn't seem to be a font/styling
> issue, either -- ? is the actual character it writes to the DOM. I have
> no idea how to diagnose or debug this...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chjj/blessed/issues/158#issuecomment-125519214>.
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by yaronn** [comment]
also try to render a blessed regular box with content which contains a braille character:

    var box = blessed.box({ 
       content: String.fromCharCode(0x2812)
    });

**Comment by chjj** [comment]
Could be an issue with term.js. @lostfictions, do the blessed-contrib characters render correctly in your native terminal?

**Comment by lostfictions** [comment]
I'm running from Ubuntu. @yaronn, that blessed box just outputs a `?` character, yeah. On the other hand, if I do this:
```javascript
  var div = document.createElement("div");
  div.innerHTML = String.fromCharCode(0x2812);
  div.style.fontFamily = '"DejaVu Sans Mono", "Liberation Mono", monospace';
  document.body.appendChild(div);
```
...the Braille character shows up just fine.

@chjj, running the same examples in my native terminal works just fine too.

**Comment by chjj** [comment]
> running the same examples in my native terminal works just fine too.

Looks like an issue with term.js then. Will investigate. That's very strange though since those braille characters are still within the BMP.

**Comment by chjj** [comment]
@lostfictions, can you try adding `LANG=en_US.UTF-8` to the term.js env and see if it makes a difference? I'm guessing your native terminal already has that env variable set, but when you run your term.js server, there is no `LANG`, and since the regular `xterm` terminfo has no `U8`, it assumes you don't support utf8.

**Comment by chjj** [comment]
Also, yes, after looking at term.js, the only reason you would get `?` in place of a BMP unicode character is if blessed cannot detect unicode either through the terminfo or `LANG` env variable. So it really just looks like a problem with configuration of your term.js server to me.

**Comment by chjj** [comment]
Hmmm, wait a second, since blessed is looking at the browserified `process.env`, try doing:

``` js
process.env.LANG = 'en_US.UTF-8';
```

Before starting up your blessed app.

**Comment by chjj** [comment]
@lostfictions, try the latest commit and add `forceUnicode: true` to the `blessed.screen()` options.

**Comment by chjj** [comment]
I've added a commit which forces unicode support when browserified.

**Comment by lostfictions** [comment]
That gets the braille characters rendering, thanks!

Unfortunately, the layout is still messed up:
![1](https://cloud.githubusercontent.com/assets/567041/8941516/085ee23e-353e-11e5-9dcb-2a2a0fcef5f0.png)
I suspected this was down to a styling issue, so I poked around in Devtools. It looks like the braille characters are actually being rendered in the non-monospace version of the font, so it's using DejaVu Sans instead of DejaVu Sans Mono. I tried using Ubuntu Mono and had the same problem.


FreeMono fares better and can render the braille characters, fixing the alignment issues, but unfortunately its braille glyphs make it unsuitable for drawing graphics:
![2-freemono](https://cloud.githubusercontent.com/assets/567041/8941596/74c42bbe-353e-11e5-99bb-f1365e53f76e.png)

Not sure why this is happening -- my terminal font is Ubuntu Mono, so it must have those Braille characters, right...?

**Comment by chjj** [comment]
As far as I know, braille characters are not double-width (term.js should have no problem rendering them), so that is undoubtedly a browser font issue.

Why does DejaVu Sans Mono not work in the browser for you? That really seems like the solution.

**Comment by chjj** [comment]
> Not sure why this is happening -- my terminal font is Ubuntu Mono, so it must have those Braille characters, right...?

Not necesarilly. Having written a terminal in C for X11, I can tell you, usually, if a font doesn't contain certain glyphs, the application will do a lookup on your fonts and iterate through them until it finds a scalable or compatible (for BMP fonts) containing those glyphs: so you're actually seeing two fonts. 

This is why unicode support is harder than it looks for native applications (which is the whole reason why rxvt was forked to rxvt-unicode - the unicode part is __non-trivial__).

Ubuntu Mono may not contain Braille glyphs, and maybe your terminal just does a better job of finding them elsewhere than your browser does.

**Comment by lostfictions** [comment]
> Why does DejaVu Sans Mono not work in the browser for you? That really seems like the solution.

I'm honestly not sure -- it seems like it must be a browser styling issue? I tried explicitly embedding DejaVu Sans Mono as a web font (making sure it wasn't subsetted) and referring to it under a different `font-family` name to ensure it was used, but no dice.

**Comment by chjj** [comment]
@lostfictions, you could try embedding a font that works with `@font-face`. That might be the best solution here.

**Comment by lostfictions** [comment]
That's what I just tried with DejaVu Sans Mono! I'm really confused as to why it's not working -- I even opened it up in FontForge and double-checked that the Braille glyphs were there just to be safe.

I'm at a total loss -- maybe there's something in the browser style engine that's causing it to be overridden? And yet FreeMono seems to work...
